### ISSUE TITLE
List of actual parameters and example events

### ISSUE THREAD

**Issue by mongonv** [kjartanvalur/angular-kendo-window#10]
Is there a list of all the parameters that can be configured in the options section and possible others?

Is there any documentation or examples on what events can be configured in setting up a window (particularly close)?

The options list seems to be a mix of bootstrap and kendo and adding a close function to the window creation operation does not seem to do anything, so trying to find out what is actually available from the creation operation and how to set them up.

Thanks much for your work
Ed

**Comment by kjartanvalur** [comment]
Hi

You can use all Kendo events that are documented here
http://docs.telerik.com/KENDO-UI/api/javascript/ui/window

But for close event it is best to use the following like in the demo (readme.md). Its so you can have direct access to parameters that you pass when you close the window.
windowInstance.result.then(function (result) {
                        // Here you can get result from the window
                    });

**Comment by mongonv** [comment]
The result.then seems to work fine for the button operations in your example script.js, but does not get called when the "X" button on the window menu bar is pressed.

Based on the kendo docs, that is what the close function in the definition is supposed to be used for, how do we trap for that when creating the window with your component?

**Comment by kjartanvalur** [comment]
Yes that is true. You can catch close event (and other Kendo events) like this.

http://plnkr.co/edit/EacLulnJbMqUffufjmgn?p=preview

$kWindow.open({
                       options:{
                         modal: true,
                         title: $scope.title,
                         resizable: true,
                         height: 150,
                         width: 400,
                         visible: false,
                         close: function(e) {
                          window.alert("Window closed");
                        }
                       },
                        templateUrl: 'modal1.html',
                        controller: 'modalController',
                        resolve: {
                            message: function () {
                                return $scope.content;
                            }
                        }

**Comment by mongonv** [comment]
Thanks much, that was the tidbit I was looking for (where to put the close bind operation) and that works great.

**Comment by kjartanvalur** [comment]
Ok good

**Comment by supruniuk** [comment]
Is it possible to maximize/minimize window automatically when the window is opened?
I tried:
    var windowInstance = $kWindow.open({...});
    windowInstance.minimize();
or
    var windowInstance = $kWindow.open({...}).minimize();
but it doesn't work
