### ISSUE TITLE
Not working on angular js version 1.2.X

### ISSUE THREAD

**Issue by sundarapandiank** [kjartanvalur/angular-kendo-window#11]
It is not supporting angular js version 1.2.x, Please let me know if there is any workaround.

**Comment by kjartanvalur** [comment]
Sorry, don´t see any quick workaround. I will look into this.

**Comment by AtahAhmed** [comment]
Any update on this ? I am using Angular js 1.4.x

**Comment by kjartanvalur** [comment]
This should work with angularjs version 1.3.0 and higher. So angular 1.4.x is supported

**Comment by kjartanvalur** [comment]
try this demo
http://plnkr.co/edit/2BfMuZT2EvQUVtxNmL8D?p=preview

**Comment by AtahAhmed** [comment]
Sorry, my mistake i didn't included window.html, which caused the issue.

**Comment by yowl** [comment]
I believe there is a problem with the templateUrl option .  On line 363 it tries to set the windowTemplateUrl from a field called "windowTemplateUrl" on the options.  But the field you set on the options is "templateUrl".  You then get an undefined and it falls back to "window.html"

**Comment by wenxiayili** [comment]
@kjartanvalur my mistake i didn't included window.html？
