### ISSUE TITLE
Keeps creating new Instance instead of using existing like Kendo Window Does

### ISSUE THREAD

**Issue by ChrisHolcomb** [kjartanvalur/angular-kendo-window#12]
I have a SPA app that I switched from using bootstrap modals to this system so I could use the Kendo Windows with a templateURL and controller.

This issue is every time you open the modal it just adds another Div to the page instead of re using the existing one like the Kendo Window does. In my template I create a Kendo DataTimePicker and set the ID because I have to manipulate the <li> items to only show specific times. Because this is creating a new instance it messes up the controller logic trying to find this specific instance.

Also since this is a SPA, over time you end up with a lot of these DIV's on the page. Is there any way to have it use the existing DIV or to destroy it's self when you close it?

**Comment by kjartanvalur** [comment]
Thanks for the info. Released version 2.2.0 with a fix
