### ISSUE TITLE
Conflict with angular-bootstrap

### ISSUE THREAD

**Issue by octavian-mirica** [kjartanvalur/angular-kendo-window#13]
I discovered this after I have struggled a lot to understand why it is not working at my side.

This module actually contains some directives (uibModalWindow, uibModalTransclude) and one factory ($uibModalStack) that are present in angular-bootstrap module (ui-bootstrap-tpls.js), which I have had already loaded into my app.

I tried to comment the code for these in angular-kendo-window.js file, but I think these "common" parts were rewritten a bit in this module, so I had to comment the code in ui-bootstrap-tpls.js to finally make it work.
I didn't investigated too much the differences, I should try a "diff" software to see exactly.

Was this intended or why wasn't this written with different directive names than angular-bootstrap's?

**Comment by kjartanvalur** [comment]
This is a very good point! Cant do this right now but if you could make pull request that would be awesome!
As I mention in readme that this is highly influenced by Angular Bootstrap modal directive.

Please also vote on [kendo uservoice](http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/11299620-angular-and-kendo-window)

**Comment by kjartanvalur** [comment]
Fixed with version 2.2.4
