### ISSUE TITLE
Alignment window

### ISSUE THREAD

**Issue by SheinEA** [kjartanvalur/angular-kendo-window#16]
Hello. Another small problem. Alignment window.

Your following code does not work:
                     var kWindow = scope.myKendoWindow.open ();
                     if (scope.options.position === undefined) {
                       kWindow.center ();
                     }
I am using the code:
                     // Todo [Shein]: Fixed alignment window
                     if (scope.options.position === undefined) {
                         scope.myKendoWindow.center ();
                     }
                     scope.myKendoWindow.open ();

**Comment by kjartanvalur** [comment]
Fixed in v.2.2.2
