### ISSUE TITLE
Latest version of kendo breaks this

### ISSUE THREAD

**Issue by paulstringerdb** [kjartanvalur/angular-kendo-window#17]
The latest build of kendo (2016.1.226) appears to break the code.
The error "Cannot read property 'open' of undefined" line 95 of "angular-kendo-window.js" is thrown.
The scope does not contain the property "myKendoWinow". Seems like the directive in the template is not setting the value of myKendoWindow onto the scope. Telerik bug maybe ?

**Comment by kjartanvalur** [comment]
Thanks I will check

**Comment by kjartanvalur** [comment]
Could not find anything wrong. Updated demo to 2016.1.226 and everything is working. Can you reproduce in plunkr?

**Comment by paulstringerdb** [comment]
Hi,

Sorry... My bad... I was inadvertently using version 3.0.0 beta of jquery which seems to be the problem. I edited my plunk from something else I was trying (face<-palm)
Like to take this opportunity to thank you for this. Its a neat feature. I think kendo (Telerik) are a bit behind the curve; their angular integration isn't brilliant (or either isn't brilliantly documented) and we're rapidly heading to an Angular 2.0 world ! This kind of stuff should be "out of the box"...

**Comment by kjartanvalur** [comment]
Thanks :)
I could not agree more! :+1:

**Comment by kjartanvalur** [comment]
And please vote if you have not already
http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/11299620-angular-and-kendo-window
