### ISSUE TITLE
timeout controller

### ISSUE THREAD

**Issue by ronnie-meijer** [kjartanvalur/angular-kendo-window#18]
I am not sure what the problem is, but when I recreate windows fast (within 1000 ms) there is some sort of controller conflict. I think it's a timeout of 1000ms, where after the controller is destroyed. 

When I make the timeout 0ms all is well.

I know that this isn't what an user would do, but while testing I stumbled on this one.

**Comment by kjartanvalur** [comment]
Hmmm. I´m using 1000ms delay to wait for closing animation. But are you creating and closing window within 1 sec?
