### ISSUE TITLE
window.html location

### ISSUE THREAD

**Issue by olman21** [kjartanvalur/angular-kendo-window#19]
Is completely necessary to have the window.html in the site root? I notice that without that file the code fails, but I'm working in MVC.NET and I can't put that file on the root, is there way to specify in the options, the location, otherwise I think that is not a correct behavior.

**Comment by kjartanvalur** [comment]
I added this option. See version 2.2.3

 var windowInstance = $kWindow.open({
                       options:{
                         modal: true,
                         title: $scope.title,
                         resizable: true,
                         height: 150,
                         width: 400,
                         visible: false
                       },
                        windowTemplateUrl: 'window.html',
                        templateUrl: 'modal1.html',
                        controller: 'modalController',
                        resolve: {
                            message: function () {
                                return $scope.content;
                            }
                        }
                    });

**Comment by arturkula** [comment]
Please update version in bower.json: it is 2.2.0 should be 2.2.3 right?
Thanks.

**Comment by kjartanvalur** [comment]
Done
