### ISSUE TITLE
Disable Escape(Esc) button functionality in kendo window

### ISSUE THREAD

**Issue by AtahAhmed** [kjartanvalur/angular-kendo-window#20]
I am using Angular JS 1.4x , Angular Material and Kendo Directives...

I am unable to disable Escape(Esc) button functionality, Research a bit but found nothing.

I don't want close the kendo-Window on clicking Esc button from keyboard.

**Comment by kjartanvalur** [comment]
This is an kendo configuration. 

You can try this.
http://stackoverflow.com/questions/24451483/disable-esc-key-on-kendo-window-popup
