### ISSUE TITLE
When closing window with window X control, promise doesn't ends

### ISSUE THREAD

**Issue by MrSkiv** [kjartanvalur/angular-kendo-window#21]
Promise doesnt call nor succes, nor error, nor notify callbacks.

**Comment by kjartanvalur** [comment]
Yes, this I know and I am looking for a way to resolve this. But you can use kendo default close event to capture all closing events but then you have no access to the result.

**Comment by MrSkiv** [comment]
I think, that when somebody closes window by X, result isn't needed at all. But it would be more consistent, if you can handle these events in single place,  something like:
windowPromise.then(function(result){//pressedok}, function(){ //window closed by dismiss or X});

If I remember right, bootstrap solved similar problem: X control is like regular button, which you can wire to any function. Maybe you can also expose some property to this close event? Or when press X, promise would return dismiss with null result?

P.S.: it is not a big problem for me - almost in all cases I can live without window close event handling.

**Comment by kjartanvalur** [comment]
ok thanks for the info. I will let you know what I come up with.

**Comment by jmuronis** [comment]
Any luck with this? I am basically using this window and have a Yes/No buttons in my view but would like a X button press or an ESC key press to also act as a "No" answer. Allowing a user to back out of this can lead to some data tracking issues for me.

**Comment by kjartanvalur** [comment]
Fixed with #30
