### ISSUE TITLE
capture the close event from the window

### ISSUE THREAD

**Issue by paddyfink** [kjartanvalur/angular-kendo-window#23]
I would like to capture the close event from the windows when the the x button is pressed.

I want to ask a confirmation to the user when he have unsaved changes before closing the windows. Is there a way to achieve that?

I tried 
 $(".k-window").kendoWindow({
    close:function(e){
        if (!confirm("are you sure?"))
        e.preventDefault();
    }
})

but it doesn't work. Any idea please?

**Comment by kjartanvalur** [comment]
this should work.
See here
http://plnkr.co/edit/Y94COX0JUdZjA6xhnw5c?p=preview

**Comment by paddyfink** [comment]
Hello,

Actually I want to be able to catch the event withing the modal controller. Basically, the modal open a form and i want to warn a user if try to close the modal without saving the form.

Is it possible? thanks again
