### ISSUE TITLE
suggestion implementing kwindow template instead of templateUrl

### ISSUE THREAD

**Issue by johnnliu** [kjartanvalur/angular-kendo-window#24]
I've found this to work quite a bit better and you don't need to upload window.html as well.

Alternatively, with webpack - template: require('window.html')

            template: '<div kendo-window="myKendoWindow" k-options="options" modal-render="{{$isRendered}}" tabindex="-1" role="dialog" >    <div><div k-window-transclude></div></div>  </div>',

            /*
            templateUrl: function (tElement, tAttrs) {
                var windowInstance = $modalStack.getTop().value;
                return windowInstance.windowTemplateUrl || 'window.html';
            },
            */

**Comment by kjartanvalur** [comment]
Hi. I have tried this and this has some issues with few controls like kEditor and kSwitch. But please if you find a way let me know
