### ISSUE TITLE
Add package.json for npm compatibility

### ISSUE THREAD

**Issue by noherczeg** [kjartanvalur/angular-kendo-window#25]
So users can install your package via NPM.

**Comment by noherczeg** [comment]
https://github.com/kjartanvalur/angular-kendo-window/pull/26

**Comment by kjartanvalur** [comment]
sorry, on a vacation. can you create it for me?

**Comment by noherczeg** [comment]
@kjartanvalur I already created a pull request for you :)

**Comment by kjartanvalur** [comment]
Well done @noherczeg  :)
