### ISSUE TITLE
Plugin not work properly

### ISSUE THREAD

**Issue by furyscript** [kjartanvalur/angular-kendo-window#28]
Hi,

I cannot update to this version because after you add the file `window.html` and change the logic, when I open a `$kWindow` on my project not work properly because it's not center vertically but only horizontally...

Also your plunker example is broken...

**Comment by noherczeg** [comment]
@furyscript I used it two days ago and it worked fine for me. Are you sure it's not your css which is missing, or overriding the defaults?

**Comment by furyscript** [comment]
I'm sure... It seems to work but popup is created at the bottom of all element and it's not properly center vertically so... @noherczeg

**Comment by noherczeg** [comment]
@furyscript I checked the plunker example and seems to be working fine for me. What's wrong in it for you?

**Comment by kjartanvalur** [comment]
The plunker example is working fine
