### ISSUE TITLE
windowClass option

### ISSUE THREAD

**Issue by durz** [kjartanvalur/angular-kendo-window#3]
What is the intended effect of the ``windowClass`` option? For example:

    $kWindow.open({
        // ...
        windowClass: 'my-class',
        // ...
    }}

Right now, supplying a class doesn't actually add a css class to the window, as one would expect. Instead, it adds ``my-class`` as the value of a ``window-class`` attribute that is on the element wrapping the window's *contents*. See screenshot:

![kwindow](https://cloud.githubusercontent.com/assets/4900094/5712696/c004aa20-9b08-11e4-9085-0a4d47afc3f4.png)

I think that it should:
- add a css class rather than just an attribute, and 
- add the css class to the actual ``k-window`` element rather than just the container of the contents

**Comment by kjartanvalur** [comment]
see 2.0 version
Now all the kendoui window options are available
