### ISSUE TITLE
How can I specify the path to window.html

### ISSUE THREAD

**Issue by pateketu** [kjartanvalur/angular-kendo-window#31]
Nice work with $kWindow!, I would like to specify path to my window.html file, how would I do that?

**Comment by kjartanvalur** [comment]
windowTemplateUrl: 'templates/windowd.html'

   var windowInstance = $kWindow.open({
                       options:{
                         ...
                       },
                       windowTemplateUrl: 'templates/window.html',
                        ....
                    });
