### ISSUE TITLE
Is it possible to change the options at runtime?

### ISSUE THREAD

**Issue by raman-kashyap** [kjartanvalur/angular-kendo-window#34]
I'm not sure but I could not find a way to modify the options like title, height, templateUrl etc. at runtime. Is it possible?

**Comment by raman-kashyap** [comment]
I was able to find a workaround by modifying the library, but it was DOM manipulation and nothing much.

**Comment by kjartanvalur** [comment]
yes. please see the demo http://plnkr.co/edit/q5ytV6ecMuq8kEv8J79y
