### ISSUE TITLE
Latest version of kendo (2017.1.118) breaks angular-kendo-window

### ISSUE THREAD

**Issue by pateketu** [kjartanvalur/angular-kendo-window#35]
Hello,

I just upgraded to latest kendo version and now I get error about myKendoWindow is undefined in the following code snippet, error is because there is no myKendowWindow on the scope for some reason

```
modalRenderDeferObj.promise.then(function () {
                    if(scope.options.position === undefined){
                    /*
                        Following line throws the error because
                        myKendowWindow is undefined
                    */
                      scope.myKendoWindow.center(); 
                    }
                    scope.myKendoWindow.open();                    
                    scope.$on($modalStack.NOW_CLOSING_EVENT, function (e, setIsAsync) {
                        scope.done = setIsAsync();
                        scope.myKendoWindow.close();
                    });
                    var modal = $modalStack.getTop();
                    if (modal) {
                        // Notify {@link $modalStack} that modal is rendered.
                        $modalStack.modalRendered(modal.key);
                    }
                });
```

Thanks
Ketul

**Comment by pateketu** [comment]
Found the problem:

So if you have Kendo UI professional version and install using NPM package described @ http://docs.telerik.com/kendo-ui/intro/installation/npm#kendo-ui-professional then you will get jQuery version 3.1.1 which essentially breaks something inside kendo and hence we no longer get myKendowWindow on the directive scope.

If you open jQuery from Telerik's CDN under it's latest version https://kendo.cdn.telerik.com/2017.1.118/js/jquery.min.js then jQuery version is 1.12.3!! and not 3.1.1 which NPM Package forces

If you use jQuery version 1.12.3 then everything works, I will test out with jQuery 2.2.4 as thats the one what kendo used to use before and check if angular-kendo-wwindow works with that

**Comment by ajbrun** [comment]
Any further thoughts on this? I've just had this after using the latest jquery version for a while, and now needing to downgrade after seeing this issue.

**Comment by kjartanvalur** [comment]
Can you provide a plunkr við this. You can fork the demo on this repo home page

**Comment by MrSkiv** [comment]
Any news on this? Have similar issue: jquery 1.12.3 - everything ok, window opens as expected, jquery 3.3.1 - window open fails (window dom is adding, but it is hidden).

**Comment by MrSkiv** [comment]
I try to debug with chrome. Fails lines:
```
 modalRenderDeferObj.promise.then(function () {
                    if(scope.options.position === undefined){
                      scope.myKendoWindow.center();
                    }
                    scope.myKendoWindow.open();
```
scope.myKendoWindow is undefined. If I look Batarang scopes: scope with same id HAS myKendoWindow property. Maybe it doesn't at the moment, when is executing myKendoWindow.Open()?

**Comment by kjartanvalur** [comment]
This is not compatible with jquery 3.x. Sorry, but all contributions are welcome.
But you can use jsquery 2.x and 1.x

**Comment by MrSkiv** [comment]
It's a pitty, cause kendo ui by itself is supporting jquery 3.1.1. [Kendo prerequisities](https://docs.telerik.com/kendo-ui/intro/installation/prerequisites)

**Comment by MrSkiv** [comment]
As a temporary solution I added delay. I hope, on slow computers it will work also:
```
modalRenderDeferObj.promise.then(function () {
                    setTimeout(function() {
                        if (scope.options.position === undefined) {
                            scope.myKendoWindow.center();
                        }
                        scope.myKendoWindow.open();

                        scope.$on($modalStack.NOW_CLOSING_EVENT,
                            function(e, setIsAsync) {
                                scope.done = setIsAsync();
                                scope.myKendoWindow.close();
                            });
                        var modal = $modalStack.getTop();
                        if (modal) {
                            // Notify {@link $modalStack} that modal is rendered.
                            $modalStack.modalRendered(modal.key);
                        }
                    }, 100);
                });
```
