### ISSUE TITLE
Can i use kendo window with AngularsJs 1.5x Component?

### ISSUE THREAD

**Issue by vitorlacerda** [kjartanvalur/angular-kendo-window#41]
Can i use kendo window with AngularsJs 1.5x Component?

Like uibModal does?  put resolve on bindings { resolve : "<" } of angularjs component.

**Comment by kjartanvalur** [comment]
Can you explain further? Like with an example
http://plnkr.co/edit/UD0mxA5ilaWMyGYGmZFr?p=preview
