### ISSUE TITLE
bower install fetches 2.2.4 and not latest release 2.2.5

### ISSUE THREAD

**Issue by PieterVanPoyer** [kjartanvalur/angular-kendo-window#42]
Hello,
I love your work.

When I do a "bower install", the next pull request is not in it. #38 
The pull request I mentioned is really important.

When I look at the releases, the master is 7 commits ahead of the release 2.2.5.
https://github.com/kjartanvalur/angular-kendo-window/releases

This is the result of the bower install. The mismatch seems odd.
`
-> bower install angular-kendo-window
bower angular-kendo-window#*       not-cached https://github.com/kjartanvalur/angular-kendo-window.git#*
bower angular-kendo-window#*          resolve https://github.com/kjartanvalur/angular-kendo-window.git#*
bower angular-kendo-window#*         download https://github.com/kjartanvalur/angular-kendo-window/archive/v2.2.5.tar.gz
bower angular-kendo-window#*          extract archive.tar.gz
bower angular-kendo-window#*         mismatch Version declared in the json (2.2.4) is different than the resolved one (2.2.5)
bower angular-kendo-window#*         resolved https://github.com/kjartanvalur/angular-kendo-window.git#2.2.5
`

How can I get the latest version, with #38 in?

Kind regards

**Comment by kjartanvalur** [comment]
can you try now?

**Comment by PieterVanPoyer** [comment]
It does not work. 

I've read the bower documentation and the 2.2.5 release points to the release tag of github.
https://github.com/kjartanvalur/angular-kendo-window/releases/tag/v2.2.5
When you download the zip of the release, it still holds 2.2.4. Because of the release tag.
(It does not fetch the master)

Maybe the only solution is to release a new version?

**Comment by kjartanvalur** [comment]
ok, what about now? :)

**Comment by PieterVanPoyer** [comment]
Jep, now he fetches the 2.2.6. Thanks for the quick intervention.
