### ISSUE TITLE
kendo editor in angular-kendo-window

### ISSUE THREAD

**Issue by JigneshChovatia** [kjartanvalur/angular-kendo-window#6]
Hi,

      i am unable to load kendo-editor in angular-kendo-window using latest version of kendo.
kendo version (2015.2.902).

Thanks
Jignesh.

**Comment by Gambero81** [comment]
I also noticed this problem with a kendo editor inside kendo window, 
when the window is opened, the source code of kendo crash in

...
wnd = iframe.contentWindow || iframe;
doc = wnd.document || iframe.contentDocument;

iframe.contenWindow is null and wnd.document is undefined so doc result null and successive doc.open() fail

any solution?
Thanks

**Comment by kjartanvalur** [comment]
check out 1.2
FYI: Now you also need window.html template
