### ISSUE TITLE
Kendo switch not work

### ISSUE THREAD

**Issue by furyscript** [kjartanvalur/angular-kendo-window#7]
Check this: http://plnkr.co/edit/b1kcPcGdS6b9uFhEEkmo?p=preview

Kendo switch not work

**Comment by kjartanvalur** [comment]
check out 1.2
FYI: Now you also need window.html template

**Comment by furyscript** [comment]
Ehm, I'm testing but I got this error
```
Error: [$compile:tplrt] Template for directive 'uibModalWindow' must have exactly one root element. window.html
http://errors.angularjs.org/1.4.4/$compile/tplrt?p0=uibModalWindow&p1=window.html
    at angular.js:68
    at angular.js:8418
    at processQueue (angular.js:14634)
    at angular.js:14650
    at Scope.$eval (angular.js:15916)
    at Scope.$digest (angular.js:15727)
    at Scope.$apply (angular.js:16024)
    at done (angular.js:10511)
    at completeRequest (angular.js:10683)
    at XMLHttpRequest.requestLoaded (angular.js:10624)
```
Also your plunker example not work...

**Comment by kjartanvalur** [comment]
Now you have to have the window.html template somewhere in your project. Default root directory.

**Comment by furyscript** [comment]
Now it works but I had to change path of window.html, and also center, draggable and resizable options not work..

**Comment by kjartanvalur** [comment]
ok, i will check that out. Thanks

**Comment by furyscript** [comment]
Thanks! If you can, notify me in this issue... :)

**Comment by kjartanvalur** [comment]
done! 1.2.2

**Comment by furyscript** [comment]
Error:
```
Template for directive 'uibModalWindow' must have exactly one root element. app/common/directives/angular-kendo-window.html
```

**Comment by kjartanvalur** [comment]
sorry. get the latest

**Comment by furyscript** [comment]
Sorry, I use 1.2.5 and it still not works D:

**Comment by kjartanvalur** [comment]
What error do you get?

**Comment by furyscript** [comment]
Nothing error the options: center, draggable, resizable, width and height not work... (all options seems to not work.. except resolve, controller and templateUrl..)
I use angular 1.4.4

**Comment by kjartanvalur** [comment]
see version 2.0. All the default kendo options are now supported. breaking changes... now kendo options are all in one options object.

**Comment by furyscript** [comment]
Not work again..
![schermata del 2015-10-29 09 27 19](https://cloud.githubusercontent.com/assets/10270403/10813466/95f7b330-7e1f-11e5-8434-d31417e90098.png)

Isn't in center, no title, no width and height etc but templateUrl works for example...

**Comment by kjartanvalur** [comment]
there are breaking changes in 2.0. see readme (notice the options object)

you can try it out in the demo:
http://plnkr.co/edit/MpvTCDikmPhL6cE3D09W?p=preview

**Comment by furyscript** [comment]
Not work..also your plunker D:

**Comment by kjartanvalur** [comment]
What does not work in the plunkr demo?

**Comment by furyscript** [comment]
There is a way to remove window.html?? And use it with bower so I manage this package with it..

**Comment by kjartanvalur** [comment]
i´m looking into removing window.html. But I get strange behaviours like e.g. kendo switch and editor not working

**Comment by kjartanvalur** [comment]
please let me know if you have a solution for this.
I will also add to bower later

**Comment by furyscript** [comment]
I don't know why for me not work, I've testing with your example and also not work, I think the problem is in window.html because templateUrl, resolve and controller works fine...

**Comment by furyscript** [comment]
Some news?:)

**Comment by kjartanvalur** [comment]
Sorry not yet
