### ISSUE TITLE
Unable to get options to work in existing app

### ISSUE THREAD

**Issue by mongonv** [kjartanvalur/angular-kendo-window#9]
I am trying to tie your directive into an existing angular 1.x app and I can get the window to open with the content message and buttons, but none of the options have any impact.  I am able to setup a barebones test app and the options work as expected, but no matter where I put the files and scripts I cannot get the options to work in my existing app.

I have the modal1.html, scripts.js, style.css, and window.html all in the root of the project.  If I remove any one of them, the window fails to open, so its seeing the files where they are located.  The only thing I have changed in the scripts.js is myApp to app (the value currently defined for the main app.)

The application has multiple controllers, screens, and code and will be growing much bigger, so we need to figure out what the issue is with your component cause we would really like to be able to use it.

Any thoughts on what to try or where to look would be greatly appreciated and thanks for a great component.

**Comment by kjartanvalur** [comment]
Hi
What do you mean you cannot get the options  to work? What options are you using? Can you give me example code? Do you get some error in browser console(developert tools)? Does the window/modal come up? Are you using any custom parameters?

**Comment by mongonv** [comment]
Sorry should have put that in, here is the function I am trying to use (its the same as the one that works):

  $scope.openWindow = function ()
  {
    var windowInstance = $kWindow.open(
      {
        options    : {
          modal    : false,
          title    : $scope.title,
          resizable: true,
          height   : 150,
          width    : 400,
          visible  : false
        },
        templateUrl: 'modal1.html',
        controller : 'modalController',
        resolve    : {
          message: function ()
          {
            return $scope.content;
          }
        }
      });

I do not get any errors or warnings in the Chrome console when I execute the function.  None of the values in the "options" section have any impact on the displayed window when called in our app.  The same calls in the simple test app work fine (window size, title, etc.)  I have not been able to find what is interfering with the passed options.

I have tried moving the placement of the inclusion of the scripts.js file, the css file, and keeping the test code from your scripts.js as pristine as possible (only changing the "MyApp" to "app" for our app) and nothing seems to have any impact on the options values having any reflection in the displayed window.  

The windows come up with the content value showing and can open multiple windows (appears the default for modal is false as that has no impact either.)

Are there any dependencies on code versions that I need to look for? (jquery, bootstrap, etc.)

Let me know if there is anything else you can think of I can try, am rather perplexed at what is interfering.

Thanks for you help and quick response.

**Comment by kjartanvalur** [comment]
Hi
This is strange. Can you try add k-ng-delay="options" to kendo window div in window.html

**Comment by mongonv** [comment]
Changes the windows.html to the following and it got much worse:

<div kendo-window="myKendoWindow" k-options="options" k-ng-delay="options" modal-render="{{$isRendered}}" tabindex="-1" role="dialog" >
    <div  ><div uib-modal-transclude></div></div>
</div>

No actual window showed, the contents of the window just got displayed at the bottom of the other html content that is on the page, so not sure what that does but it was not happy about it.

I am running the latest kendo release now and it does seem to be working fine, so if you just let people know which version is the min version could save trouble.  It may be some issue in the actual kendo code, not sure.

**Comment by kjartanvalur** [comment]
Ok good. What version were you using?
Remember to vote 
http://kendoui-feedback.telerik.com/forums/127393-telerik-kendo-ui-feedback/suggestions/11299620-angular-and-kendo-window

**Comment by mongonv** [comment]
The original version was Kendo UI v2015.2.805 pro.

Right now using the latest version V2016.1.112 which seems to be working fine.

Did now know there was a voting thing, will do it for sure.

Thanks for the great component and support

**Comment by kjartanvalur** [comment]
No problem :)
